# Generated by Django 6.0.3 on 2026-03-06 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='cleaned_file',
            field=models.FileField(blank=True, null=True, upload_to='cleaned_datasets/'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='top_kpis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='level',
            field=models.CharField(choices=[('basic', 'Basic'), ('advanced', 'Advanced')], default='basic', max_length=10),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='column_names',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='file_type',
            field=models.CharField(blank=True, choices=[('csv', 'CSV'), ('excel', 'Excel')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='analysis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='analytics.analysis'),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(blank=True, choices=[('sales', 'Sales'), ('hr', 'HR'), ('financial', 'Financial'), ('custom', 'Custom')], max_length=20, null=True)),
                ('goal', models.CharField(blank=True, choices=[('find_trends', 'Find Trends'), ('predict_outcomes', 'Predict Outcomes'), ('custom', 'Custom')], max_length=50, null=True)),
                ('target_column', models.CharField(blank=True, max_length=255, null=True)),
                ('dashboard_level', models.CharField(blank=True, choices=[('basic', 'Basic'), ('advanced', 'Advanced')], max_length=10, null=True)),
                ('download_code', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='analytics.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='analytics.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='chat_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis', to='analytics.chatsession'),
        ),
        migrations.CreateModel(
            name='ExportedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('pdf', 'PDF Report'), ('ipynb', 'Jupyter Notebook'), ('py', 'Python Script')], max_length=10)),
                ('file', models.FileField(upload_to='exports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='analytics.dashboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
